const initialState = {
  items: [
    {
      food_id: 1,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1bdKKaTySsc4t8ahzTXQIG87Ls_J8ph907w&s",
      name: "Margherita Pizza",
      description:
        "Classic Italian pizza with fresh mozzarella, tomatoes, and basil",
      price: 7.99,
      isVeg: true,
      category: "Pizza",
      offers: ["Buy 1 Get 1 Free on Wednesdays", "10% off for new customers"],
      ingredients: [
        "Tomato sauce",
        "Mozzarella",
        "Basil",
        "Olive oil",
        "Pizza crust",
      ],
    },
    {
      food_id: 2,
      name: "Pepperoni Pizza",
      img: "https://www.simplyrecipes.com/thmb/KE6iMblr3R2Db6oE8HdyVsFSj2A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__09__easy-pepperoni-pizza-lead-3-1024x682-583b275444104ef189d693a64df625da.jpg",
      description: "Loaded with spicy pepperoni and extra cheese",
      price: 9.49,
      isVeg: true,
      category: "Pizza",
      offers: ["Flat 20% off for students", "Free drink with large pizza"],
      ingredients: ["Tomato sauce", "Mozzarella", "Pepperoni", "Pizza crust"],
    },
    {
      food_id: 3,
      name: "BBQ Chicken Pizza",
      img: "https://www.allrecipes.com/thmb/qZ7LKGV1_RYDCgYGSgfMn40nmks=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-24878-bbq-chicken-pizza-beauty-4x3-39cd80585ad04941914dca4bd82eae3d.jpg",
      description: "Grilled chicken, BBQ sauce, onions, and cheddar cheese",
      price: 10.99,
      isVeg: false,
      category: "Pizza",
      offers: [
        "Buy any medium, get small free",
        "Flat $5 off on orders above $30",
      ],
      ingredients: [
        "BBQ sauce",
        "Grilled chicken",
        "Onions",
        "Cheddar cheese",
        "Pizza crust",
      ],
    },
    {
      food_id: 4,
      name: "Veggie Supreme Pizza",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaLabHCgyK_q1WcBUU_vGfEIZnPj_6lJ9-Ig&s",
      description:
        "Loaded with bell peppers, onions, mushrooms, olives, and tomatoes",
      price: 8.99,
      isVeg: true,
      category: "Pizza",
      offers: ["15% off on all veggie pizzas", "Extra toppings free"],
      ingredients: [
        "Tomato sauce",
        "Mozzarella",
        "Bell peppers",
        "Onions",
        "Mushrooms",
        "Olives",
        "Tomatoes",
        "Pizza crust",
      ],
    },
    {
      food_id: 5,
      name: "Meat Lover’s Pizza",
      img: "https://www.thespruceeats.com/thmb/xuxwh4RIGcZMgaJE8u3SueM0SoA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/aqIMG_4568fhor-0b89dc5c8c494ee9828ed29805791c5a.jpg",
      description: "A combination of pepperoni, sausage, bacon, and ham",
      price: 11.49,
      isVeg: false,
      category: "Pizza",
      offers: [
        "Free garlic bread with any large pizza",
        "20% off for premium members",
      ],
      ingredients: [
        "Tomato sauce",
        "Mozzarella",
        "Pepperoni",
        "Sausage",
        "Bacon",
        "Ham",
        "Pizza crust",
      ],
    },
    {
      food_id: 6,
      name: "Hawaiian Pizza",
      img: "https://outgrilling.com/wp-content/uploads/2024/02/Easy-Hawaiian-Pizza-Recipe-Image-F.jpg",
      description: "A tropical mix of pineapple, ham, and mozzarella",
      price: 9.29,
      isVeg: true,
      category: "Pizza",
      offers: ["Flat 10% off on Hawaiian pizzas", "Buy 2 get 1 half price"],
      ingredients: [
        "Tomato sauce",
        "Mozzarella",
        "Pineapple",
        "Ham",
        "Pizza crust",
      ],
    },
    {
      food_id: 7,
      name: "Four Cheese Pizza",
      img: "https://kitchenatics.com/wp-content/uploads/2020/09/Cheese-pizza-1.jpg",
      description:
        "A rich blend of mozzarella, cheddar, parmesan, and blue cheese",
      price: 10.49,
      isVeg: true,
      category: "Pizza",
      offers: ["Extra cheese free", "25% off for cheese lovers"],
      ingredients: [
        "Tomato sauce",
        "Mozzarella",
        "Cheddar",
        "Parmesan",
        "Blue cheese",
        "Pizza crust",
      ],
    },
    {
      food_id: 8,
      name: "Buffalo Chicken Pizza",
      img: "https://www.allrecipes.com/thmb/GK6zZbKChUTMmq9vHhGMbyPbQGA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/BuffaloChickenPizza_AR_Feb-Mar-24x3-07e2fcb74a1d472499f4c22980825b13.jpg",
      description: "Spicy buffalo sauce with grilled chicken and ranch drizzle",
      price: 10.79,
      isVeg: false,
      category: "Pizza",
      offers: ["Flat $3 off on large size", "Free ranch dip with every order"],
      ingredients: [
        "Buffalo sauce",
        "Grilled chicken",
        "Mozzarella",
        "Ranch dressing",
        "Pizza crust",
      ],
    },
    {
      food_id: 9,
      name: "Truffle Mushroom Pizza",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtrTlnGBnpxcosRrNgNXUk2T4wtCXueG22Bw&s",
      description:
        "Gourmet truffle-infused mushrooms with mozzarella and parmesan",
      price: 12.99,
      isVeg: true,
      category: "Pizza",
      offers: ["Luxury Deal: 15% off", "Free extra truffle oil drizzle"],
      ingredients: [
        "Truffle mushrooms",
        "Mozzarella",
        "Parmesan",
        "Garlic sauce",
        "Pizza crust",
      ],
    },
    {
      food_id: 10,
      name: "Mediterranean Pizza",
      img: "https://tastyoven.com/wp-content/uploads/2023/05/mediterranean-pizza-image-1.jpg",
      description:
        "A fresh mix of feta cheese, olives, sun-dried tomatoes, and basil",
      price: 11.29,
      isVeg: true,
      category: "Pizza",
      offers: ["Exclusive 20% off for Mediterranean menu", "Free hummus dip"],
      ingredients: [
        "Tomato sauce",
        "Mozzarella",
        "Feta cheese",
        "Olives",
        "Sun-dried tomatoes",
        "Basil",
        "Pizza crust",
      ],
    },
    {
      food_id: 11,
      name: "Classic Cheeseburger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFExWftHhBK07UkiHZykqbo1RFUZEa2ecFgg&s",
      description:
        "Juicy beef patty with melted cheese, lettuce, tomato, and special sauce",
      price: 5.99,
      isVeg: false,
      category: "Burger",
      offers: ["10% off on first order", "Buy 1 Get 1 Free on Fridays"],
      ingredients: [
        "Beef patty",
        "Cheese",
        "Lettuce",
        "Tomato",
        "Bun",
        "Sauce",
      ],
    },
    {
      food_id: 12,
      name: "BBQ Bacon Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description:
        "Smoky BBQ sauce, crispy bacon, cheddar cheese, and caramelized onions",
      price: 7.49,
      isVeg: false,
      category: "Burger",
      offers: ["Flat 20% off for members", "Free fries with combo"],
      ingredients: [
        "Beef patty",
        "Bacon",
        "BBQ sauce",
        "Cheddar cheese",
        "Onions",
        "Bun",
      ],
    },
    {
      food_id: 13,
      name: "Mushroom Swiss Burger",
      img: "https://groundbeefrecipes.com/wp-content/uploads/mushroom-swiss-burgers.jpg",
      description:
        "Grilled mushrooms, Swiss cheese, and garlic aioli on a toasted bun",
      price: 6.99,
      isVeg: true,
      category: "Burger",
      offers: ["Free drink with large meal", "Weekend Special: 15% off"],
      ingredients: [
        "Beef patty",
        "Mushrooms",
        "Swiss cheese",
        "Garlic aioli",
        "Bun",
      ],
    },
    {
      food_id: 14,
      name: "Spicy Jalapeno Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRufvcC7zpKOKecp-VKOcF4NU6SLbG7tHLonQ&s",
      description: "Spicy jalapenos, pepper jack cheese, and chipotle mayo",
      price: 6.49,
      isVeg: true,
      category: "Burger",
      offers: ["Happy Hour: 25% off", "Buy 2 Get 1 Free"],
      ingredients: [
        "Beef patty",
        "Jalapenos",
        "Pepper jack cheese",
        "Chipotle mayo",
        "Bun",
      ],
    },
    {
      food_id: 15,
      name: "Double Decker Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Two juicy beef patties, double cheese, and house sauce",
      price: 8.99,
      isVeg: false,
      category: "Burger",
      offers: ["Extra cheese free on request", "Combo meal at $10.99"],
      ingredients: [
        "Double beef patty",
        "Cheese",
        "Lettuce",
        "Tomato",
        "House sauce",
        "Bun",
      ],
    },
    {
      food_id: 16,
      name: "Crispy Chicken Burger",
      img: "https://groundbeefrecipes.com/wp-content/uploads/mushroom-swiss-burgers.jpg",
      description: "Crispy fried chicken with coleslaw and spicy mayo",
      price: 6.99,
      isVeg: false,
      category: "Burger",
      offers: [
        "Student Discount: 10% off",
        "Free soft drink with large burger",
      ],
      ingredients: ["Fried chicken", "Coleslaw", "Spicy mayo", "Bun"],
    },
    {
      food_id: 17,
      name: "Grilled Chicken Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Healthy grilled chicken breast with avocado and lettuce",
      price: 7.29,
      isVeg: false,
      category: "Burger",
      offers: ["20% off for gym members", "No extra charge for avocado"],
      ingredients: [
        "Grilled chicken",
        "Avocado",
        "Lettuce",
        "Tomato",
        "Whole wheat bun",
      ],
    },
    {
      food_id: 18,
      name: "Veggie Delight Burger",
      img: "https://groundbeefrecipes.com/wp-content/uploads/mushroom-swiss-burgers.jpg",
      description: "A tasty vegetarian patty with fresh veggies and cheese",
      price: 5.99,
      isVeg: true,
      category: "Burger",
      offers: [
        "Flat 15% off on all veggie items",
        "Free upgrade to large fries",
      ],
      ingredients: [
        "Veggie patty",
        "Cheese",
        "Lettuce",
        "Tomato",
        "Cucumber",
        "Bun",
      ],
    },
    {
      food_id: 19,
      name: "Paneer Tikka Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Spicy grilled paneer with mint mayo and onions",
      price: 6.49,
      isVeg: true,
      category: "Burger",
      offers: ["Buy 1 Get 1 at 50% off", "Extra paneer topping free"],
      ingredients: ["Grilled paneer", "Mint mayo", "Onions", "Bun"],
    },
    {
      food_id: 20,
      name: "Fish Fillet Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Crispy fish fillet with tartar sauce and lettuce",
      price: 6.99,
      isVeg: false,
      category: "Burger",
      offers: ["Loyalty members get 20% off", "Free fries on Wednesdays"],
      ingredients: ["Fish fillet", "Tartar sauce", "Lettuce", "Bun"],
    },
    {
      food_id: 21,
      name: "Buffalo Chicken Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Crispy chicken tossed in buffalo sauce with ranch dressing",
      price: 7.29,
      isVeg: true,
      category: "Burger",
      offers: ["$5 off on orders above $20", "Extra sauce free"],
      ingredients: ["Crispy chicken", "Buffalo sauce", "Ranch dressing", "Bun"],
    },
    {
      food_id: 22,
      name: "Truffle Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Premium beef patty with truffle aioli and arugula",
      price: 9.99,
      isVeg: false,
      category: "Burger",
      offers: ["Exclusive: 15% off luxury burgers", "Free cheese upgrade"],
      ingredients: ["Beef patty", "Truffle aioli", "Arugula", "Brioche bun"],
    },
    {
      food_id: 23,
      name: "Egg & Cheese Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Fried egg, melted cheese, and a beef patty",
      price: 6.49,
      isVeg: false,
      category: "Burger",
      offers: ["Breakfast Special: 10% off", "Free coffee with combo"],
      ingredients: ["Egg", "Beef patty", "Cheese", "Bun"],
    },
    {
      food_id: 24,
      name: "Hawaiian Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Grilled pineapple, ham, and Swiss cheese on a juicy patty",
      price: 7.79,
      isVeg: true,
      category: "Burger",
      offers: ["10% off on tropical burgers", "Free fruit punch with meal"],
      ingredients: ["Beef patty", "Pineapple", "Ham", "Swiss cheese", "Bun"],
    },
    {
      food_id: 25,
      name: "Keto Protein Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Bun-less burger with lettuce wrap and extra protein",
      price: 8.49,
      isVeg: true,
      category: "Burger",
      offers: ["Healthy Combo: Free salad", "15% off for keto club members"],
      ingredients: [
        "Beef patty",
        "Lettuce wrap",
        "Avocado",
        "Tomato",
        "Cheese",
      ],
    },
    {
      food_id: 26,
      name: "Mexican Salsa Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description: "Zesty salsa, jalapenos, and guacamole with a juicy patty",
      price: 7.49,
      isVeg: true,
      category: "Burger",
      offers: [
        "Fiesta Deal: 20% off on all Mexican flavors",
        "Free nachos on orders above $15",
      ],
      ingredients: ["Beef patty", "Salsa", "Jalapenos", "Guacamole", "Bun"],
    },
    {
      food_id: 27,
      name: "Teriyaki Chicken Burger",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yno8NdtmvvOznE9cdilZnJ06SjtJzkfBRw&s",
      description:
        "Teriyaki-glazed chicken with grilled pineapple and sesame sauce",
      price: 7.29,
      isVeg: true,
      category: "Burger",
      offers: ["Flat $2 off on Asian flavors", "Free side salad"],
      ingredients: [
        "Grilled chicken",
        "Teriyaki sauce",
        "Pineapple",
        "Sesame sauce",
        "Bun",
      ],
    },
    {
      food_id: 28,
      name: "Cheese Overload Burger",
      img: "https://www.createwithnestle.ph/sites/default/files/srh_recipes/440a9c7206d782751c58f17fb1c798c9.jpg",
      description:
        "Loaded with 4 types of cheese for an ultimate cheesy experience",
      price: 8.99,
      isVeg: true,
      category: "Burger",
      offers: ["Extra cheese free", "25% off on cheese lovers' menu"],
      ingredients: [
        "Beef patty",
        "Cheddar",
        "Swiss",
        "Mozzarella",
        "Blue cheese",
        "Bun",
      ],
    },
    {
      food_id: 29,
      name: "Classic Hakka Noodles",
      img: "https://img-global.cpcdn.com/recipes/fc1a6ef23b258749/680x482cq70/classic-hakka-noodles-recipe-main-photo.jpg",
      description: "Stir-fried noodles with vegetables and soy sauce",
      price: 6.99,
      isVeg: true,
      category: "Noodles",
      offers: ["10% off on first order", "Free drink with large size"],
      ingredients: [
        "Noodles",
        "Cabbage",
        "Carrot",
        "Capsicum",
        "Soy sauce",
        "Garlic",
      ],
    },
    {
      food_id: 30,
      name: "Schezwan Noodles",
      img: "https://cdn.jhattse.com/resize?width=3840&url=https://media-assets.swiggy.com/swiggy/image/upload/07564b754d856b14692f5dbad4d4d1b9&quality=75&type=webp",
      description: "Spicy noodles tossed with Schezwan sauce and vegetables",
      price: 7.49,
      isVeg: true,
      category: "Noodles",
      offers: ["Flat 15% off on all spicy dishes", "Extra Schezwan sauce free"],
      ingredients: [
        "Noodles",
        "Carrot",
        "Bell peppers",
        "Schezwan sauce",
        "Garlic",
      ],
    },
    {
      food_id: 31,
      name: "Chicken Chow Mein",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHAMC0Z2G27sK1SKFD1ex2-qqmOW7WLm7kCQ&s",
      description:
        "Chinese-style stir-fried noodles with chicken and vegetables",
      price: 8.99,
      isVeg: false,
      category: "Noodles",
      offers: ["Free spring rolls with large meal", "Weekend Special: 20% off"],
      ingredients: [
        "Noodles",
        "Chicken",
        "Cabbage",
        "Carrot",
        "Soy sauce",
        "Garlic",
      ],
    },
    {
      food_id: 32,
      name: "Garlic Butter Noodles",
      img: "https://www.allrecipes.com/thmb/gPoIy93WTKfIT1IMKKdIActgclQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-11920-garlic-butter-sauce-I-DDMFS-4x3-241d90b6bd354ffaba320df7abcdb5c4.jpg",
      description: "Rich and flavorful noodles with butter and garlic",
      price: 7.29,
      isVeg: true,
      category: "Noodles",
      offers: ["Buy 2 Get 1 Free", "Flat $2 off on orders above $20"],
      ingredients: [
        "Noodles",
        "Garlic",
        "Butter",
        "Soy sauce",
        "Spring onions",
      ],
    },
    {
      food_id: 33,
      name: "Pad Thai",
      img: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_16:9/k%2FPhoto%2FRecipes%2F2024-04-pad-thai-190%2Fpad-thai-190-251",
      description:
        "Traditional Thai-style noodles with peanuts, tofu, and tamarind sauce",
      price: 9.49,
      isVeg: true,
      category: "Noodles",
      offers: ["Flat 20% off for Thai food lovers", "Extra tofu free"],
      ingredients: [
        "Rice noodles",
        "Tofu",
        "Peanuts",
        "Tamarind sauce",
        "Bean sprouts",
      ],
    },
    {
      food_id: 34,
      name: "Dragon Noodles",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHAMC0Z2G27sK1SKFD1ex2-qqmOW7WLm7kCQ&s",
      description: "Fiery noodles with chili sauce, garlic, and sesame seeds",
      price: 8.79,
      isVeg: true,
      category: "Noodles",
      offers: ["Spicy Challenge: 15% off", "Free lemonade with order"],
      ingredients: [
        "Noodles",
        "Chili sauce",
        "Garlic",
        "Sesame seeds",
        "Spring onions",
      ],
    },
    {
      food_id: 35,
      name: "Egg Hakka Noodles",
      img: "https://theyummydelights.com/wp-content/uploads/2021/04/egg-hakka-noodles-5-1.jpg",
      description:
        "Chinese-style noodles tossed with scrambled eggs and vegetables",
      price: 7.99,
      isVeg: false,
      category: "Noodles",
      offers: ["Flat 10% off on all egg dishes", "Extra egg topping free"],
      ingredients: [
        "Noodles",
        "Eggs",
        "Capsicum",
        "Carrot",
        "Soy sauce",
        "Garlic",
      ],
    },
    {
      food_id: 36,
      name: "Teriyaki Noodles",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY4AKnoOCWUwhxRLWQGwhzWHcMRHgybLB9Cg&s",
      description:
        "Japanese-style noodles with teriyaki sauce and sesame seeds",
      price: 8.49,
      isVeg: true,
      category: "Noodles",
      offers: [
        "Flat 10% off for loyalty members",
        "Free miso soup with large meal",
      ],
      ingredients: [
        "Noodles",
        "Teriyaki sauce",
        "Sesame seeds",
        "Spring onions",
        "Garlic",
      ],
    },
    {
      food_id: 37,
      name: "Seafood Noodles",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY4AKnoOCWUwhxRLWQGwhzWHcMRHgybLB9Cg&s",
      description: "Delicious noodles with shrimp, squid, and Asian spices",
      price: 10.99,
      isVeg: false,
      category: "Noodles",
      offers: ["Exclusive: 15% off on seafood menu", "Free drink with order"],
      ingredients: [
        "Noodles",
        "Shrimp",
        "Squid",
        "Garlic",
        "Soy sauce",
        "Spring onions",
      ],
    },
    {
      food_id: 38,
      name: "Veg Thai Noodles",
      img: "https://www.thespruceeats.com/thmb/kpnl0p1hMBsESB9wbWRN_0Zdoc4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/thai-stir-fried-noodles-with-vegetables-3217111_hero_01-8f13deb4bcb84fca82f244a504b0d886.jpg",
      description:
        "Thai-style noodles with coconut milk, lemongrass, and fresh vegetables",
      price: 8.29,
      isVeg: true,
      category: "Noodles",
      offers: ["Flat $3 off on large meals", "Extra veggies free"],
      ingredients: [
        "Rice noodles",
        "Coconut milk",
        "Lemongrass",
        "Tofu",
        "Carrot",
        "Bell peppers",
      ],
    },
      {
        food_id: 39,
        name: "Chocolate Lava Cake",
        img: "https://www.melskitchencafe.com/wp-content/uploads/2023/01/updated-lava-cakes7.jpg",
        description: "Warm chocolate cake with a gooey molten chocolate center",
        price: 6.49,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Buy 1 Get 1 Free on weekends",
          "Flat 10% off for first-time buyers",
        ],
        ingredients: [
          "Flour",
          "Cocoa powder",
          "Butter",
          "Sugar",
          "Eggs",
          "Chocolate ganache",
        ],
      },
      {
        food_id: 40,
        name: "Classic Cheesecake",
        img: "https://www.allrecipes.com/thmb/5_r5-GuF1KQxOs2nrW4EF4F-4ak=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-155222-philadelphia-classic-cheesecake-4x3-hero-5e8c2187a57a4016b5934058ad7d9b5e.jpg",
        description: "Creamy cheesecake with a graham cracker crust",
        price: 7.99,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Flat 15% off on all cheesecakes",
          "Free fruit topping of choice",
        ],
        ingredients: [
          "Cream cheese",
          "Sugar",
          "Eggs",
          "Graham cracker crust",
          "Vanilla extract",
        ],
      },
      {
        food_id: 41,
        name: "Tiramisu",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwbKMWvt1_GuwGDFCF0VBM_uI3_pAUQL3tyw&s",
        description:
          "Italian coffee-flavored dessert with layers of mascarpone and cocoa",
        price: 8.29,
        isVeg: true,
        category: "Dessert",
        offers: ["Flat $2 off on orders above $20", "Extra cocoa dusting free"],
        ingredients: [
          "Ladyfingers",
          "Espresso",
          "Mascarpone cheese",
          "Cocoa powder",
          "Sugar",
        ],
      },
      {
        food_id: 42,
        name: "Brownie Sundae",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9O8KWV8Y7sSMtuOouVyPJd01IwKbmoVoqrg&s",
        description:
          "Chocolate brownie topped with vanilla ice cream and hot fudge",
        price: 6.99,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Free extra scoop of ice cream",
          "20% off for premium members",
        ],
        ingredients: [
          "Brownie",
          "Vanilla ice cream",
          "Hot fudge",
          "Whipped cream",
          "Chopped nuts",
        ],
      },
      {
        food_id: 43,
        name: "Fruit Trifle",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUJurahk4oQfuTR0P5Dfxt6r1luQgHcrqy8Q&s",
        description: "Layers of sponge cake, custard, and mixed fruits",
        price: 7.49,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Flat 10% off on all fruity desserts",
          "Extra fruit toppings free",
        ],
        ingredients: [
          "Sponge cake",
          "Custard",
          "Strawberries",
          "Blueberries",
          "Whipped cream",
        ],
      },
      {
        food_id: 44,
        name: "Red Velvet Cake",
        img: "https://cruff.in/cdn/shop/files/hearty-red-velvet-cake.webp?v=1731494478",
        description: "Moist red velvet cake layered with cream cheese frosting",
        price: 8.79,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Buy 2 slices, get 1 free",
          "Flat $5 off on whole cake orders",
        ],
        ingredients: [
          "Flour",
          "Cocoa powder",
          "Butter",
          "Sugar",
          "Eggs",
          "Cream cheese frosting",
        ],
      },
      {
        food_id: 45,
        name: "Panna Cotta",
        img: "https://www.allrecipes.com/thmb/NlP50cO2BjJdN4uGvl5JhW0Rx2A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-72567-Panna-cotta-ddmfs-4x3-14ae724a2a8e4ca3a79c5e27b2b61994.jpg",
        description: "Silky smooth Italian dessert made with vanilla and cream",
        price: 7.99,
        isVeg: true,
        category: "Dessert",
        offers: ["Flat 15% off on all Italian desserts", "Free berry topping"],
        ingredients: [
          "Heavy cream",
          "Sugar",
          "Vanilla extract",
          "Gelatin",
          "Berries",
        ],
      },
      {
        food_id: 46,
        name: "Churros with Chocolate Dip",
        img: "https://www.jonathanmelendez.com/wp-content/uploads/2016/11/0S9A10018-2024x1349-1.jpg",
        description: "Crispy fried churros served with rich chocolate sauce",
        price: 6.49,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Flat 10% off on all Spanish desserts",
          "Extra chocolate dip free",
        ],
        ingredients: [
          "Flour",
          "Butter",
          "Sugar",
          "Cinnamon",
          "Chocolate sauce",
        ],
      },
      {
        food_id: 47,
        name: "Mango Sticky Rice",
        img: "https://www.allrecipes.com/thmb/yeUwoCu2irwqGDb-3PHJHnaX2C4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-150313-thai-sweet-sticky-rice-with-mango-khao-neeo-mamuang-ddmfs-4x3-hero-0da7a9b26cce4d07aea44f2f2b6abd95.jpg",
        description:
          "Sweet Thai dessert with coconut-flavored sticky rice and mango slices",
        price: 8.49,
        isVeg: true,
        category: "Dessert",
        offers: ["Flat 20% off on Thai desserts", "Extra coconut cream free"],
        ingredients: [
          "Sticky rice",
          "Coconut milk",
          "Mango",
          "Sugar",
          "Sesame seeds",
        ],
      },
      {
        food_id: 48,
        name: "Gulab Jamun",
        img: "https://theartisticcook.com/wp-content/uploads/2024/10/Gulab-Jamun-with-Milk-Powder.jpg",
        description:
          "Traditional Indian dessert made with deep-fried milk dumplings soaked in syrup",
        price: 5.99,
        isVeg: true,
        category: "Dessert",
        offers: [
          "Buy 1 Get 1 Free on festival days",
          "Flat $2 off on orders above $15",
        ],
        ingredients: [
          "Milk solids",
          "Flour",
          "Sugar syrup",
          "Cardamom",
          "Rose water",
        ],
      },
    ],
};

//  menu items reducer

export default function menu_reducer(state = initialState, action) {
  switch (action.type) {
    case "menu/add_menu_item":
      return { ...state, items: [action.payload, ...state.items] };
    case "menu/remove_menu_item":
      return {
        ...state,
        items: state.items.filter((food) => food.food_id !== action.payload),
      };
    default:
      return state;
  }
}

// action creators functions

export function add_menu_item(obj) {
  return { type: "menu/add_menu_item", payload: obj };
}

export function remove_menu_item(id) {
  return { type: "menu/remove_item", payload: id };
}
