[
  {
    food_id: 1,
    name: "Margherita Pizza",
    description:
      "Classic Italian pizza with fresh mozzarella, tomatoes, and basil",
    price: 7.99,
    isVeg: true,
    category: "Pizza",
    offers: ["Buy 1 Get 1 Free on Wednesdays", "10% off for new customers"],
    ingredients: [
      "Tomato sauce",
      "Mozzarella",
      "Basil",
      "Olive oil",
      "Pizza crust",
    ],
  },
  {
    food_id: 2,
    name: "Pepperoni Pizza",
    description: "Loaded with spicy pepperoni and extra cheese",
    price: 9.49,
    isVeg: true,
    category: "Pizza",
    offers: ["Flat 20% off for students", "Free drink with large pizza"],
    ingredients: ["Tomato sauce", "Mozzarella", "Pepperoni", "Pizza crust"],
  },
  {
    food_id: 3,
    name: "BBQ Chicken Pizza",
    description: "Grilled chicken, BBQ sauce, onions, and cheddar cheese",
    price: 10.99,
    isVeg: false,
    category: "Pizza",
    offers: [
      "Buy any medium, get small free",
      "Flat $5 off on orders above $30",
    ],
    ingredients: [
      "BBQ sauce",
      "Grilled chicken",
      "Onions",
      "Cheddar cheese",
      "Pizza crust",
    ],
  },
  {
    food_id: 4,
    name: "Veggie Supreme Pizza",
    description:
      "Loaded with bell peppers, onions, mushrooms, olives, and tomatoes",
    price: 8.99,
    isVeg: true,
    category: "Pizza",
    offers: ["15% off on all veggie pizzas", "Extra toppings free"],
    ingredients: [
      "Tomato sauce",
      "Mozzarella",
      "Bell peppers",
      "Onions",
      "Mushrooms",
      "Olives",
      "Tomatoes",
      "Pizza crust",
    ],
  },
  {
    food_id: 5,
    name: "Meat Lover’s Pizza",
    description: "A combination of pepperoni, sausage, bacon, and ham",
    price: 11.49,
    isVeg: false,
    category: "Pizza",
    offers: [
      "Free garlic bread with any large pizza",
      "20% off for premium members",
    ],
    ingredients: [
      "Tomato sauce",
      "Mozzarella",
      "Pepperoni",
      "Sausage",
      "Bacon",
      "Ham",
      "Pizza crust",
    ],
  },
  {
    food_id: 6,
    name: "Hawaiian Pizza",
    description: "A tropical mix of pineapple, ham, and mozzarella",
    price: 9.29,
    isVeg: true,
    category: "Pizza",
    offers: ["Flat 10% off on Hawaiian pizzas", "Buy 2 get 1 half price"],
    ingredients: [
      "Tomato sauce",
      "Mozzarella",
      "Pineapple",
      "Ham",
      "Pizza crust",
    ],
  },
  {
    food_id: 7,
    name: "Four Cheese Pizza",
    description:
      "A rich blend of mozzarella, cheddar, parmesan, and blue cheese",
    price: 10.49,
    isVeg: true,
    category: "Pizza",
    offers: ["Extra cheese free", "25% off for cheese lovers"],
    ingredients: [
      "Tomato sauce",
      "Mozzarella",
      "Cheddar",
      "Parmesan",
      "Blue cheese",
      "Pizza crust",
    ],
  },
  {
    food_id: 8,
    name: "Buffalo Chicken Pizza",
    description: "Spicy buffalo sauce with grilled chicken and ranch drizzle",
    price: 10.79,
    isVeg: false,
    category: "Pizza",
    offers: ["Flat $3 off on large size", "Free ranch dip with every order"],
    ingredients: [
      "Buffalo sauce",
      "Grilled chicken",
      "Mozzarella",
      "Ranch dressing",
      "Pizza crust",
    ],
  },
  {
    food_id: 9,
    name: "Truffle Mushroom Pizza",
    description:
      "Gourmet truffle-infused mushrooms with mozzarella and parmesan",
    price: 12.99,
    isVeg: true,
    category: "Pizza",
    offers: ["Luxury Deal: 15% off", "Free extra truffle oil drizzle"],
    ingredients: [
      "Truffle mushrooms",
      "Mozzarella",
      "Parmesan",
      "Garlic sauce",
      "Pizza crust",
    ],
  },
  {
    food_id: 10,
    name: "Mediterranean Pizza",
    description:
      "A fresh mix of feta cheese, olives, sun-dried tomatoes, and basil",
    price: 11.29,
    isVeg: true,
    category: "Pizza",
    offers: ["Exclusive 20% off for Mediterranean menu", "Free hummus dip"],
    ingredients: [
      "Tomato sauce",
      "Mozzarella",
      "Feta cheese",
      "Olives",
      "Sun-dried tomatoes",
      "Basil",
      "Pizza crust",
    ],
  },
  {
    food_id: 11,
    name: "Classic Cheeseburger",
    description:
      "Juicy beef patty with melted cheese, lettuce, tomato, and special sauce",
    price: 5.99,
    isVeg: false,
    category: "Burger",
    offers: ["10% off on first order", "Buy 1 Get 1 Free on Fridays"],
    ingredients: ["Beef patty", "Cheese", "Lettuce", "Tomato", "Bun", "Sauce"],
  },
  {
    food_id: 12,
    name: "BBQ Bacon Burger",
    description:
      "Smoky BBQ sauce, crispy bacon, cheddar cheese, and caramelized onions",
    price: 7.49,
    isVeg: false,
    category: "Burger",
    offers: ["Flat 20% off for members", "Free fries with combo"],
    ingredients: [
      "Beef patty",
      "Bacon",
      "BBQ sauce",
      "Cheddar cheese",
      "Onions",
      "Bun",
    ],
  },
  {
    food_id: 13,
    name: "Mushroom Swiss Burger",
    description:
      "Grilled mushrooms, Swiss cheese, and garlic aioli on a toasted bun",
    price: 6.99,
    isVeg: true,
    category: "Burger",
    offers: ["Free drink with large meal", "Weekend Special: 15% off"],
    ingredients: [
      "Beef patty",
      "Mushrooms",
      "Swiss cheese",
      "Garlic aioli",
      "Bun",
    ],
  },
  {
    food_id: 14,
    name: "Spicy Jalapeno Burger",
    description: "Spicy jalapenos, pepper jack cheese, and chipotle mayo",
    price: 6.49,
    isVeg: true,
    category: "Burger",
    offers: ["Happy Hour: 25% off", "Buy 2 Get 1 Free"],
    ingredients: [
      "Beef patty",
      "Jalapenos",
      "Pepper jack cheese",
      "Chipotle mayo",
      "Bun",
    ],
  },
  {
    food_id: 15,
    name: "Double Decker Burger",
    description: "Two juicy beef patties, double cheese, and house sauce",
    price: 8.99,
    isVeg: false,
    category: "Burger",
    offers: ["Extra cheese free on request", "Combo meal at $10.99"],
    ingredients: [
      "Double beef patty",
      "Cheese",
      "Lettuce",
      "Tomato",
      "House sauce",
      "Bun",
    ],
  },
  {
    food_id: 16,
    name: "Crispy Chicken Burger",
    description: "Crispy fried chicken with coleslaw and spicy mayo",
    price: 6.99,
    isVeg: false,
    category: "Burger",
    offers: ["Student Discount: 10% off", "Free soft drink with large burger"],
    ingredients: ["Fried chicken", "Coleslaw", "Spicy mayo", "Bun"],
  },
  {
    food_id: 17,
    name: "Grilled Chicken Burger",
    description: "Healthy grilled chicken breast with avocado and lettuce",
    price: 7.29,
    isVeg: false,
    category: "Burger",
    offers: ["20% off for gym members", "No extra charge for avocado"],
    ingredients: [
      "Grilled chicken",
      "Avocado",
      "Lettuce",
      "Tomato",
      "Whole wheat bun",
    ],
  },
  {
    food_id: 18,
    name: "Veggie Delight Burger",
    description: "A tasty vegetarian patty with fresh veggies and cheese",
    price: 5.99,
    isVeg: true,
    category: "Burger",
    offers: ["Flat 15% off on all veggie items", "Free upgrade to large fries"],
    ingredients: [
      "Veggie patty",
      "Cheese",
      "Lettuce",
      "Tomato",
      "Cucumber",
      "Bun",
    ],
  },
  {
    food_id: 19,
    name: "Paneer Tikka Burger",
    description: "Spicy grilled paneer with mint mayo and onions",
    price: 6.49,
    isVeg: true,
    category: "Burger",
    offers: ["Buy 1 Get 1 at 50% off", "Extra paneer topping free"],
    ingredients: ["Grilled paneer", "Mint mayo", "Onions", "Bun"],
  },
  {
    food_id: 20,
    name: "Fish Fillet Burger",
    description: "Crispy fish fillet with tartar sauce and lettuce",
    price: 6.99,
    isVeg: false,
    category: "Burger",
    offers: ["Loyalty members get 20% off", "Free fries on Wednesdays"],
    ingredients: ["Fish fillet", "Tartar sauce", "Lettuce", "Bun"],
  },
  {
    food_id: 21,
    name: "Buffalo Chicken Burger",
    description: "Crispy chicken tossed in buffalo sauce with ranch dressing",
    price: 7.29,
    isVeg: true,
    category: "Burger",
    offers: ["$5 off on orders above $20", "Extra sauce free"],
    ingredients: ["Crispy chicken", "Buffalo sauce", "Ranch dressing", "Bun"],
  },
  {
    food_id: 22,
    name: "Truffle Burger",
    description: "Premium beef patty with truffle aioli and arugula",
    price: 9.99,
    isVeg: false,
    category: "Burger",
    offers: ["Exclusive: 15% off luxury burgers", "Free cheese upgrade"],
    ingredients: ["Beef patty", "Truffle aioli", "Arugula", "Brioche bun"],
  },
  {
    food_id: 23,
    name: "Egg & Cheese Burger",
    description: "Fried egg, melted cheese, and a beef patty",
    price: 6.49,
    isVeg: false,
    category: "Burger",
    offers: ["Breakfast Special: 10% off", "Free coffee with combo"],
    ingredients: ["Egg", "Beef patty", "Cheese", "Bun"],
  },
  {
    food_id: 24,
    name: "Hawaiian Burger",
    description: "Grilled pineapple, ham, and Swiss cheese on a juicy patty",
    price: 7.79,
    isVeg: true,
    category: "Burger",
    offers: ["10% off on tropical burgers", "Free fruit punch with meal"],
    ingredients: ["Beef patty", "Pineapple", "Ham", "Swiss cheese", "Bun"],
  },
  {
    food_id: 25,
    name: "Keto Protein Burger",
    description: "Bun-less burger with lettuce wrap and extra protein",
    price: 8.49,
    isVeg: true,
    category: "Burger",
    offers: ["Healthy Combo: Free salad", "15% off for keto club members"],
    ingredients: ["Beef patty", "Lettuce wrap", "Avocado", "Tomato", "Cheese"],
  },
  {
    food_id: 26,
    name: "Mexican Salsa Burger",
    description: "Zesty salsa, jalapenos, and guacamole with a juicy patty",
    price: 7.49,
    isVeg: true,
    category: "Burger",
    offers: [
      "Fiesta Deal: 20% off on all Mexican flavors",
      "Free nachos on orders above $15",
    ],
    ingredients: ["Beef patty", "Salsa", "Jalapenos", "Guacamole", "Bun"],
  },
  {
    food_id: 27,
    name: "Teriyaki Chicken Burger",
    description:
      "Teriyaki-glazed chicken with grilled pineapple and sesame sauce",
    price: 7.29,
    isVeg: true,
    category: "Burger",
    offers: ["Flat $2 off on Asian flavors", "Free side salad"],
    ingredients: [
      "Grilled chicken",
      "Teriyaki sauce",
      "Pineapple",
      "Sesame sauce",
      "Bun",
    ],
  },
  {
    food_id: 28,
    name: "Cheese Overload Burger",
    description:
      "Loaded with 4 types of cheese for an ultimate cheesy experience",
    price: 8.99,
    isVeg: true,
    category: "Burger",
    offers: ["Extra cheese free", "25% off on cheese lovers' menu"],
    ingredients: [
      "Beef patty",
      "Cheddar",
      "Swiss",
      "Mozzarella",
      "Blue cheese",
      "Bun",
    ],
  },
  {
    food_id: 29,
    name: "Classic Hakka Noodles",
    description: "Stir-fried noodles with vegetables and soy sauce",
    price: 6.99,
    isVeg: true,
    category: "Noodles",
    offers: ["10% off on first order", "Free drink with large size"],
    ingredients: [
      "Noodles",
      "Cabbage",
      "Carrot",
      "Capsicum",
      "Soy sauce",
      "Garlic",
    ],
  },
  {
    food_id: 30,
    name: "Schezwan Noodles",
    description: "Spicy noodles tossed with Schezwan sauce and vegetables",
    price: 7.49,
    isVeg: true,
    category: "Noodles",
    offers: ["Flat 15% off on all spicy dishes", "Extra Schezwan sauce free"],
    ingredients: [
      "Noodles",
      "Carrot",
      "Bell peppers",
      "Schezwan sauce",
      "Garlic",
    ],
  },
  {
    food_id: 31,
    name: "Chicken Chow Mein",
    description: "Chinese-style stir-fried noodles with chicken and vegetables",
    price: 8.99,
    isVeg: false,
    category: "Noodles",
    offers: ["Free spring rolls with large meal", "Weekend Special: 20% off"],
    ingredients: [
      "Noodles",
      "Chicken",
      "Cabbage",
      "Carrot",
      "Soy sauce",
      "Garlic",
    ],
  },
  {
    food_id: 32,
    name: "Garlic Butter Noodles",
    description: "Rich and flavorful noodles with butter and garlic",
    price: 7.29,
    isVeg: true,
    category: "Noodles",
    offers: ["Buy 2 Get 1 Free", "Flat $2 off on orders above $20"],
    ingredients: ["Noodles", "Garlic", "Butter", "Soy sauce", "Spring onions"],
  },
  {
    food_id: 33,
    name: "Pad Thai",
    description:
      "Traditional Thai-style noodles with peanuts, tofu, and tamarind sauce",
    price: 9.49,
    isVeg: true,
    category: "Noodles",
    offers: ["Flat 20% off for Thai food lovers", "Extra tofu free"],
    ingredients: [
      "Rice noodles",
      "Tofu",
      "Peanuts",
      "Tamarind sauce",
      "Bean sprouts",
    ],
  },
  {
    food_id: 34,
    name: "Dragon Noodles",
    description: "Fiery noodles with chili sauce, garlic, and sesame seeds",
    price: 8.79,
    isVeg: true,
    category: "Noodles",
    offers: ["Spicy Challenge: 15% off", "Free lemonade with order"],
    ingredients: [
      "Noodles",
      "Chili sauce",
      "Garlic",
      "Sesame seeds",
      "Spring onions",
    ],
  },
  {
    food_id: 35,
    name: "Egg Hakka Noodles",
    description:
      "Chinese-style noodles tossed with scrambled eggs and vegetables",
    price: 7.99,
    isVeg: false,
    category: "Noodles",
    offers: ["Flat 10% off on all egg dishes", "Extra egg topping free"],
    ingredients: [
      "Noodles",
      "Eggs",
      "Capsicum",
      "Carrot",
      "Soy sauce",
      "Garlic",
    ],
  },
  {
    food_id: 36,
    name: "Teriyaki Noodles",
    description: "Japanese-style noodles with teriyaki sauce and sesame seeds",
    price: 8.49,
    isVeg: true,
    category: "Noodles",
    offers: [
      "Flat 10% off for loyalty members",
      "Free miso soup with large meal",
    ],
    ingredients: [
      "Noodles",
      "Teriyaki sauce",
      "Sesame seeds",
      "Spring onions",
      "Garlic",
    ],
  },
  {
    food_id: 37,
    name: "Seafood Noodles",
    description: "Delicious noodles with shrimp, squid, and Asian spices",
    price: 10.99,
    isVeg: false,
    category: "Noodles",
    offers: ["Exclusive: 15% off on seafood menu", "Free drink with order"],
    ingredients: [
      "Noodles",
      "Shrimp",
      "Squid",
      "Garlic",
      "Soy sauce",
      "Spring onions",
    ],
  },
  {
    food_id: 38,
    name: "Veg Thai Noodles",
    description:
      "Thai-style noodles with coconut milk, lemongrass, and fresh vegetables",
    price: 8.29,
    isVeg: true,
    category: "Noodles",
    offers: ["Flat $3 off on large meals", "Extra veggies free"],
    ingredients: [
      "Rice noodles",
      "Coconut milk",
      "Lemongrass",
      "Tofu",
      "Carrot",
      "Bell peppers",
    ],
  },
  [
    {
      food_id: 39,
      name: "Chocolate Lava Cake",
      description: "Warm chocolate cake with a gooey molten chocolate center",
      price: 6.49,
      isVeg: true,
      category: "Dessert",
      offers: [
        "Buy 1 Get 1 Free on weekends",
        "Flat 10% off for first-time buyers",
      ],
      ingredients: [
        "Flour",
        "Cocoa powder",
        "Butter",
        "Sugar",
        "Eggs",
        "Chocolate ganache",
      ],
    },
    {
      food_id: 40,
      name: "Classic Cheesecake",
      description: "Creamy cheesecake with a graham cracker crust",
      price: 7.99,
      isVeg: true,
      category: "Dessert",
      offers: [
        "Flat 15% off on all cheesecakes",
        "Free fruit topping of choice",
      ],
      ingredients: [
        "Cream cheese",
        "Sugar",
        "Eggs",
        "Graham cracker crust",
        "Vanilla extract",
      ],
    },
    {
      food_id: 41,
      name: "Tiramisu",
      description:
        "Italian coffee-flavored dessert with layers of mascarpone and cocoa",
      price: 8.29,
      isVeg: true,
      category: "Dessert",
      offers: ["Flat $2 off on orders above $20", "Extra cocoa dusting free"],
      ingredients: [
        "Ladyfingers",
        "Espresso",
        "Mascarpone cheese",
        "Cocoa powder",
        "Sugar",
      ],
    },
    {
      food_id: 42,
      name: "Brownie Sundae",
      description:
        "Chocolate brownie topped with vanilla ice cream and hot fudge",
      price: 6.99,
      isVeg: true,
      category: "Dessert",
      offers: ["Free extra scoop of ice cream", "20% off for premium members"],
      ingredients: [
        "Brownie",
        "Vanilla ice cream",
        "Hot fudge",
        "Whipped cream",
        "Chopped nuts",
      ],
    },
    {
      food_id: 43,
      name: "Fruit Trifle",
      description: "Layers of sponge cake, custard, and mixed fruits",
      price: 7.49,
      isVeg: true,
      category: "Dessert",
      offers: [
        "Flat 10% off on all fruity desserts",
        "Extra fruit toppings free",
      ],
      ingredients: [
        "Sponge cake",
        "Custard",
        "Strawberries",
        "Blueberries",
        "Whipped cream",
      ],
    },
    {
      food_id: 44,
      name: "Red Velvet Cake",
      description: "Moist red velvet cake layered with cream cheese frosting",
      price: 8.79,
      isVeg: true,
      category: "Dessert",
      offers: ["Buy 2 slices, get 1 free", "Flat $5 off on whole cake orders"],
      ingredients: [
        "Flour",
        "Cocoa powder",
        "Butter",
        "Sugar",
        "Eggs",
        "Cream cheese frosting",
      ],
    },
    {
      food_id: 45,
      name: "Panna Cotta",
      description: "Silky smooth Italian dessert made with vanilla and cream",
      price: 7.99,
      isVeg: true,
      category: "Dessert",
      offers: ["Flat 15% off on all Italian desserts", "Free berry topping"],
      ingredients: [
        "Heavy cream",
        "Sugar",
        "Vanilla extract",
        "Gelatin",
        "Berries",
      ],
    },
    {
      food_id: 46,
      name: "Churros with Chocolate Dip",
      description: "Crispy fried churros served with rich chocolate sauce",
      price: 6.49,
      isVeg: true,
      category: "Dessert",
      offers: [
        "Flat 10% off on all Spanish desserts",
        "Extra chocolate dip free",
      ],
      ingredients: ["Flour", "Butter", "Sugar", "Cinnamon", "Chocolate sauce"],
    },
    {
      food_id: 47,
      name: "Mango Sticky Rice",
      description:
        "Sweet Thai dessert with coconut-flavored sticky rice and mango slices",
      price: 8.49,
      isVeg: true,
      category: "Dessert",
      offers: ["Flat 20% off on Thai desserts", "Extra coconut cream free"],
      ingredients: [
        "Sticky rice",
        "Coconut milk",
        "Mango",
        "Sugar",
        "Sesame seeds",
      ],
    },
    {
      food_id: 48,
      name: "Gulab Jamun",
      description:
        "Traditional Indian dessert made with deep-fried milk dumplings soaked in syrup",
      price: 5.99,
      isVeg: true,
      category: "Dessert",
      offers: [
        "Buy 1 Get 1 Free on festival days",
        "Flat $2 off on orders above $15",
      ],
      ingredients: [
        "Milk solids",
        "Flour",
        "Sugar syrup",
        "Cardamom",
        "Rose water",
      ],
    },
  ],
];
